#!/usr/bin/env ruby

system("vi lib/marsdate.rb +/VER '+sil norm|$4h'")

require 'date'

$LOAD_PATH << "./lib"

today = Date.today.strftime("%Y-%m-%d")

system("git pull")
gs = `git status 2>&1`

if gs =~ /not staged for commit/
  puts
  puts gs
  puts "\n\n Possible bad git status. Continue? (y/n)"
  resp = gets.chomp
  case resp 
    when "y"
      system("git add -u")
      print "Commit message = "
      msg = gets.chomp
      system("git commit -m '#{msg}' && git push")
      puts "Now continuing..."
    else         # assume "no"
      puts "Exiting.\n "
      exit
  end
else
  print "Commit message = "
  msg = gets.chomp
  system("git commit -m '#{msg}' && git push")
end

update = <<-EOF
  gem build marsdate.gemspec && 
  gem push marsdate-*.gem && 
  gem uninstall -x marsdate && 
  gem install marsdate
EOF

system(update)

